services:

  spring-api-image:
    image: spring-api-image
    container_name: spring-api-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - spring-network
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres_database
    environment:
      POSTGRES_DB: shortening_url
      POSTGRES_USER: martinpc
      POSTGRES_PASSWORD: martinpc
    ports:
      - "5432:5432"
    networks:
      - spring-network
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  spring-network:
volumes:
  db-data: